-- =================================================================
-- reset_admin.sql
-- WARNING: This script is DESTRUCTIVE. It will permanently delete
-- all data and drop all objects (tables, views, etc.) in the
-- YAHYA_ADMIN schema.
--
-- It then creates a minimal set of tables for a single admin user.
-- =================================================================

SET SERVEROUTPUT ON;
SET ECHO ON;
WHENEVER SQLERROR CONTINUE;

-- Step 1: Drop all existing objects in the schema
PROMPT -----------------------------------------------------------------
PROMPT Dropping all objects in the schema...
PROMPT -----------------------------------------------------------------
BEGIN
    -- Drop views
    FOR v IN (SELECT view_name FROM user_views) LOOP
        EXECUTE IMMEDIATE 'DROP VIEW ' || v.view_name;
    END LOOP;
    
    -- Drop procedures, functions, packages
    FOR p IN (SELECT object_name FROM user_objects WHERE object_type IN ('PROCEDURE', 'FUNCTION', 'PACKAGE')) LOOP
        EXECUTE IMMEDIATE 'DROP ' || p.object_type || ' ' || p.object_name;
    END LOOP;

    -- Drop tables (dependencies are handled by CASCADE CONSTRAINTS)
    FOR t IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
    
    -- Drop remaining sequences
    FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('>>> Cleanup phase complete.');
END;
/

PROMPT -----------------------------------------------------------------
PROMPT Step 2: Create minimal tables for admin account...
PROMPT -----------------------------------------------------------------

CREATE TABLE user_account (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_code VARCHAR2(30) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(10) NOT NULL,
    status VARCHAR2(10) DEFAULT 'ACTIVE',
    CONSTRAINT chk_user_role_reset
        CHECK (role IN ('STUDENT','PROF','ADMIN'))
);

CREATE TABLE admin (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(30) UNIQUE NOT NULL,
    full_name VARCHAR2(100),
    CONSTRAINT fk_admin_user_reset
        FOREIGN KEY (username)
        REFERENCES user_account(login_code)
);

PROMPT >>> Tables user_account and admin created.

PROMPT -----------------------------------------------------------------
PROMPT Step 3: Create the admin/admin user...
PROMPT -----------------------------------------------------------------
INSERT INTO user_account (login_code, password_hash, role, status) VALUES ('admin', 'admin', 'ADMIN', 'ACTIVE');
INSERT INTO admin (username, full_name) VALUES ('admin', 'Default Admin');

PROMPT >>> User admin/admin created.

PROMPT -----------------------------------------------------------------
PROMPT Committing changes...
PROMPT -----------------------------------------------------------------
COMMIT;

PROMPT >>> Reset complete.
